### ISSUE TITLE
Getting an Error

### ISSUE THREAD

**Issue by priyasood** [Call-for-Code/node-red-contrib-twc-covid19-tracker#1]
![Nodered-Error](https://user-images.githubusercontent.com/26269420/80320231-d87c7980-8832-11ea-8533-492f31ec11c3.PNG)

Hi John, While Importing this Node-RED-covid19-dashboard.json flow and covid19-api-test.json flow getting the same error attached?

**Comment by johnwalicki** [comment]
Hi Priya - Did you register for a TWC Api key? You need to enter it into the diease tracker node.  The missing pwsapi node is the hidden config node that stores the api key.

**Comment by johnwalicki** [comment]
In my v0.1.0 implementation, the node-red-contrib-twc-weather and node-red-contrib-twc-covid19-tracker share the hidden pwsapikey configuration node so that you can share the TWC api key and only enter it once.  This seems to cause all sorts of problems (works on my development system because I have both packages installed).  Overall, this was a bad idea.  Node-RED packages should not share configuration nodes.

I have a v0.2.0 fix that splits out the TWC api key (which might be entitled to both Weather API and the Covid-19 API) into separate hidden pwsapikey and covapikey configuration nodes.  You can certainly use the same API key for both weather and covid BUT you'll need enter it separately into the distinct nodes.

**Comment by johnwalicki** [comment]
I'm trying to figure out how to deploy this fix.
I have staged a bunch of new work for v0.2.0 in anticipation of adding a new node to the node-red-contrib-twc-covid19-tracker - (There's a Country Reports API coming tomorrow),  it has new screenshots, new example flows, I swapped from request to got for network requests.

If folks don't mind waiting 1 day for the critical fix, it will be a clean deployment.

In the interrim today, 04-27-2020, you can 
```npm install node-red-contrib-twc-weather```
that will install the hidden pwsapikey config node and the covid19-disease-tracker node will work (until the config nodes split out in v0.2.0)

**Comment by johnwalicki** [comment]
My test system ALSO had both packages installed even though I was testing in separate Node-RED project flows.  Annoyed that I missed this in my test suite.  It seemed like a brilliant idea. v0.2.0 should repair it.

**Comment by johnwalicki** [comment]
node-red-contrib-twc-covid19-tracker v0.2.0 has been posted to npm.
The fix for this problem report is included in v0.2.0
Closing issue.
