### ISSUE TITLE
TypeError: Cannot read property 'recordLocation' of undefined

### ISSUE THREAD

**Issue by mridulrb** [Call-for-Code/node-red-contrib-twc-covid19-tracker#3]
In Node-RED-covid19-dashboard.json for Build Table function for TWC COVI, recordLocation is undefined so we are not able to generate the tables for Country Reports. 
<img width="1433" alt="COVID-19_Node-RED" src="https://user-images.githubusercontent.com/12492961/82139556-a52d7900-9839-11ea-86f5-31b28ee47d4f.png">
<img width="1324" alt="COVID-19_Dashboard" src="https://user-images.githubusercontent.com/12492961/82139562-ab235a00-9839-11ea-83e0-65a29a1ae9e9.png">

**Comment by johnwalicki** [comment]
Hi Mridul - The error is occurring because the API key you entered is incorrect / invalid.  Can you check that you correctly pasted the API key you received from callforcode.weather.com into the configuration node? The Arkansas chart makes me believe that the API key is valid but you might not have selected the key in the TWC COVID-19 Country Report node....

**Comment by mridulrb** [comment]
Hi John - I have verified the API key again and it appears to be correct. I have attached screenshots for your reference. 
<img width="1433" alt="Screen Shot 2020-05-18 at 11 51 55 AM" src="https://user-images.githubusercontent.com/12492961/82187781-fbfc8680-98fd-11ea-9ec6-b59e9ab0f159.png">
<img width="1433" alt="Screen Shot 2020-05-18 at 11 52 11 AM" src="https://user-images.githubusercontent.com/12492961/82187819-04ed5800-98fe-11ea-80a8-4c6bf35ad28e.png">
<img width="1433" alt="Screen Shot 2020-05-18 at 11 52 34 AM" src="https://user-images.githubusercontent.com/12492961/82187848-120a4700-98fe-11ea-8830-caf4a1dd7253.png">
